const axios = require('axios');
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const port = 5001;

const cors = require('cors');
app.use(cors()); // This allows cross-origin requests


// Middleware to parse JSON request body
app.use(bodyParser.json());

// API Route to Generate Report
app.post('/generate-report', async (req, res) => {
  const { userInput } = req.body;

  // Check if userInput exists
  if (!userInput) {
    return res.status(400).json({ error: 'User input is required' });
  }

  try {
    // Make request to Hugging Face API
    const response = await axios.post(
      'https://api-inference.huggingface.co/models/gpt2', // GPT-2 model from Hugging Face
      {
        inputs: userInput, // The input you want to send to the model
      },
      {
        headers: {
          Authorization: `Bearer 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`, //  Hugging Face API key 
        },
      }
    );

    // Check if response data is available
    if (response.data?.[0]?.generated_text) {
      res.json({ report: response.data[0].generated_text });
    } else {
      res.status(500).json({ error: 'No text generated by the model' });
    }
  } catch (error) {
    // Error handling
    console.error('Error generating report:', error);
    res.status(500).json({ error: 'Error generating report' });
  }
});

// Start server
app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});

