// updated server.js backend file, created using node.js
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const { GoogleGenerativeAI } = require("@google/generative-ai");

const app = express();
const port = 5001;

const GOOGLE_API_KEY = "AIzaSyAwKFza9NMXUFb9qEJsxCYP6e0TLO50jJs"; // my google gemini api key
const genAI = new GoogleGenerativeAI(GOOGLE_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro-latest"});

// we use cors to allow access from different origins(different ports)
app.use(cors());
app.use(bodyParser.json());

// API Route to Generate Report
app.post('/generate-report', async (req, res) => {
  const { userInput } = req.body;

  if (!userInput) {
    return res.status(400).json({ error: 'User input is required' });
  }

  try {
    // Generate content using Google Gemini
    const result = await model.generateContent(userInput);
    const responseText = result.response.text();

    if (responseText) {
      res.json({ report: responseText });
    } else {
      res.status(500).json({ error: 'No text generated by Gemini' });
    }
  } catch (error) {
    console.error('Error generating report:', error.message);
    res.status(500).json({ error: 'Error generating report' });
  }
});

// Start server
app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
